### ISSUE TITLE
Help setting the database

### ISSUE THREAD

**Issue by MatheusParanhos** [NodeFactoryIo/node-ts-starter#1]
Hi, I just crossed over this repo and want to say thank you for this pearl! 
Very clean and it will save me hours. ^^

I'm a bit new in this docker world and i'm having a few trouble setting up the database for local development. How would I proceed to setup postgres inside a docker and it's users and roles? 
I'm getting this error when doing so:

> nodejs-db  | FATAL:  password authentication failed for user "postgres"
> nodejs-db  | DETAIL:  Role "postgres" does not exist.

Any help? Thanks!

**Comment by MatheusParanhos** [comment]
Guys please, I'm having difficulties when connecting the database from docker-compose. What are the steps that I have to do in order to connect the database when developing locally? Any lights would be greatly apreciatted! thanks again
@mpetrunic

**Comment by mpetrunic** [comment]
Sorry, was weekend :) 
If you didn't create `.env` file, database was probably created with default params (everything "nodefactory"). If you change POSTGRES_USER, POSTGRES_PASSWORD or POSTGRES_DB just delete directory called .mysql in project structure and restart docker-compose

**Comment by MatheusParanhos** [comment]
Hi @mpetrunic not at all! I've managed to set up envs and all! thanks!
Now I'm trying to figure it out the best way to push this repo to production using aws ecr and aws ecs. How to build it for production? I know it's unrelated but have you used this repo with any aws services? Thanks man!

**Comment by mpetrunic** [comment]
Yeah I did. Install aws cli in circleci or better yet find/create some docker image with aws cli preinstalled. In deploy step of circleci it builds the production ready image (without dev dependencies and source code) called `final`. You can tag this final image with aws ecr name and push it to aws ecr registry. If your ecs task uses latest image just use aws cli to update ecs service.

**Comment by MatheusParanhos** [comment]
@mpetrunic Thank you. Would you care to share a gist of your circleci.yml for this? Thank you again it's been a great help

**Comment by MatheusParanhos** [comment]
@mpetrunic Hi again.. I think I've made it to push to ecr adding these lines to `deploy step`:

`    - run:
        name: Install aws
        command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - run:
        name: "Log in to AWS ECR"
        command: $(aws ecr get-login --no-include-email --region us-west-1)
    - run:
        name: "Build & Push Docker Image"
        command: |
          docker tag nodefactory/nodejs-ts-starter:latest repositorylink:latest
          docker push repositorylink:latest`

after this in circleci I should use aws cli to update the ecs service, then right?
If I manage to make the deploy smoothly can I fork this repo to add configs for deploying in aws? or perhaps you can branch it ˆˆ

**Comment by mpetrunic** [comment]
Deployment should be something like this:
https://gist.github.com/mpetrunic/d2c813be65c48e7017a315dce1b951bd

Feel free to open PR on branch aws-deployment because not everyone uses aws for deployment to it's very env specific.

If you like our repo share it with friends and colleagues :)
